In [9]:
import numpy as np

# From a Python list
arr1 = np.array([1, 2, 3, 4, 5])  

# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  

# Array of zeros
zeros = np.zeros((3, 3))  

# Array of ones
ones = np.ones((2, 4))  

# Identity matrix
identity = np.eye(3)  

# Range of values (similar to range())
range_arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)   # (2, 3) → 2 rows, 3 columns  
print(arr.ndim)    # 2 → dimensions (2D)  
print(arr.size)    # 6 → total elements  
print(arr.dtype)   # int64 → data type  

(2, 3)
2
6
int64


In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5, 7, 9]  
print(a * b)  # [4, 10, 18]  
print(np.sqrt(a))  # [1., 1.414, 1.732]  

[5 7 9]
[ 4 10 18]
[1.         1.41421356 1.73205081]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))    # 15  
print(np.mean(arr))   # 3.0  
print(np.max(arr))    # 5  
print(np.min(arr))    # 1  
print(np.std(arr))    # 1.414 (standard deviation)  

In [6]:
arr = np.arange(1, 10)  # [1, 2, 3, 4, 5, 6, 7, 8, 9]  

# Reshape to 3x3 matrix
reshaped = arr.reshape(3, 3)  

# Stacking arrays vertically
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked = np.vstack((a, b))  # [[1,2,3], [4,5,6]]  

# Stacking horizontally
hstacked = np.hstack((a, b))  # [1,2,3,4,5,6]  

In [7]:
# Random float between 0 and 1
rand_float = np.random.random()  

# Random integers (low, high, size)
rand_ints = np.random.randint(1, 100, 5)  # [23, 56, 12, 89, 45]  

# Random normal distribution (mean=0, std=1)
normal_dist = np.random.normal(0, 1, 10)  

In [ ]:
8. Practical Applications in Data Science
Data cleaning (handling missing values, filtering)
Numerical computations (statistics, linear algebra)
Image processing (arrays represent pixel values)
Machine learning (input data for models)

In [ ]:
9.NumPy Practice:

In [ ]:
Basic Array Operations:
 >Create a 1D array with numbers from 0 to 9.
 >Create a 3×3 matrix filled with 5s.
 >Create an array of 10 random integers between 1 and 100.

In [8]:
import numpy as np

# 1. Create a 1D array from 0 to 9
arr1 = np.arange(10)

# 2. Create a 3×3 matrix of 5s
arr2 = np.full((3, 3), 5)

# 3. Array of 10 random integers (1-100)
arr3 = np.random.randint(1, 101, 10)

In [ ]:
Indexing and Slicing:
 >Given the array arr = np.arange(10, 100, 10), extract:
   The first element
   The last element
   Elements from index 3 to 6
   Every alternate element
 >For the 2D array matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), extract:
   The second row
   The third column
   The element at row 1, column 2

In [ ]:
arr = np.arange(10, 100, 10)  # [10, 20, 30, 40, 50, 60, 70, 80, 90]

# 4. 
first = arr[0]          # 10
last = arr[-1]          # 90
sliced = arr[3:7]       # [40, 50, 60, 70]
alternate = arr[::2]    # [10, 30, 50, 70, 90]

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 5. 
second_row = matrix[1]        # [4, 5, 6]
third_col = matrix[:, 2]      # [3, 6, 9]
element = matrix[1, 2]        # 6

In [ ]:
Array Manipulation:
 >Reverse the array arr = np.array([1, 2, 3, 4, 5]).
 >Reshape the array arr = np.arange(12) into a 3×4 matrix.
 >Flatten the 2D array matrix = np.array([[1, 2], [3, 4]]) into a 1D array.

In [ ]:
# 6. Reverse an array
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]  # [5, 4, 3, 2, 1]

# 7. Reshape into 3×4
arr = np.arange(12)
reshaped = arr.reshape(3, 4)

# 8. Flatten a 2D array
matrix = np.array([[1, 2], [3, 4]])
flattened = matrix.flatten()  # [1, 2, 3, 4]

In [ ]:
Mathematical Operations
 >Given a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]), compute:
   Element-wise addition
   Element-wise multiplication
   Dot product
 >Compute the mean, median, and standard deviation of arr = np.array([5, 10, 15, 20, 25]).

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 9. 
add = a + b          # [5, 7, 9]
multiply = a * b     # [4, 10, 18]
dot_product = np.dot(a, b)  # 32 (1*4 + 2*5 + 3*6)

# 10. 
arr = np.array([5, 10, 15, 20, 25])
mean = np.mean(arr)       # 15.0
median = np.median(arr)   # 15.0
std = np.std(arr)         # 7.071

In [ ]:
Boolean Indexing
 >From arr = np.array([10, 20, 30, 40, 50]), extract all elements greater than 25.
 >Replace all odd numbers in arr = np.array([1, 2, 3, 4, 5]) with -1.

In [ ]:
# 11. Extract elements > 25
arr = np.array([10, 20, 30, 40, 50])
filtered = arr[arr > 25]  # [30, 40, 50]

# 12. Replace odd numbers with -1
arr = np.array([1, 2, 3, 4, 5])
arr[arr % 2 == 1] = -1    # [-1, 2, -1, 4, -1]